config/routes.rb
Cgray::Application.routes.draw do

  resources :sitemap do 
    collection do 
      get :basic
      get :jobfairs
      get :jobs
      get :employers
      get :static
    end
  end

  resources :users, :controller => "user"
  
  resources :sessions, :controller => 'session' do
    collection do
      get :password_reminder 
    end
  end

  resources :authentications, :controller => 'authentication' do
    collection do
      post :link
    end
  end

  resources :applicants, :controller=> 'applicant' do 

    collection do
      get  :deactivate
      post :process_deactivation 
    end

    member do 
      post :apply 
      post :enable_social_login
      get  :photo
    end
  end

  resources :connections do
    member do
      get :photo
    end
  end

  resources :employers, :controller => 'employer' do

    collection do
      get :job_fairs 
      get :services
    end

    member  do  
      get :public_profile 
    end

    resources :recruiters, :controller => 'recruiter' do 
      member do
        get :current_status 
        get :dashboard 
      end
    end

    resources :ofccp do 
      collection do
        post :download_to_excel
        post :download 
      end
    end

  end

  resources :jobs do 
    
    collection do 
      get :search 
      get :quick_search 
      post :auto_complete_for_employer_name 
    end

	member do 
      get :repost 
      get :apply 
      get :apply_notify
      get :add_to_inbox
      get :remove_from_inbox 
      get :public_profile 
    end

  end

  resources :resumes do 

    collection do 
      get :search
      get :quick_search 
      get :guest_search
      get :guest_index
    end

	member do 
      get :add_to_inbox 
      get :remove_from_inbox 
      get :print 
     post :forward 
      get :download 
      get :attachment 
    end
  end

  resources :positions do
    member do
      post :validate
    end
  end

  resources :educations do
    member do
      post :validate
    end
  end

  resources :jobfairs, :controller => "jobfair" do 
    member do 
      get :registered_employers 
    end

	   resources :registrations
  end

  resources :messages

  resources :registrations do
    collection do 
      get  :new_from_affiliate 
      post :post_from_affiliate 
    end
  end

  
  namespace :admin do 

    resources :jobfairs

	   resources :registrations do
      member do 
        get :enable_search 
      end
    end

    resources :employers do
      member do 
        post :administrator_name 
      end

      resources :recruiters do 
        collection do 
          get :download_to_excel 
        end
      end

      resources :jobs
    end

    resources :recruiters do 
      collection do 
        post :auto_complete_for_employer_name 
        post :update_employer 
        get  :edit_employer
      end
    end

    resources :applicants do 
      collection do 
        post :upload
        post :download_to_excel 
      end

    end

    resources :resumes do 
      collection do
        get :search 
      end

      member do 
        get :download 
        get :attachment 
       post :forward
      end

    end

    resources :users do 
      member do
        get :skip_email_verification 
      end
    end

	   resources :ofccp do
      collection do 
        post :download_to_excel 
      end
    end

  end 
  
  
  root :to => 'welcome#index'
  match 'welcome' => 'welcome#index', :as => 'welcome' 

  match 'admin' => "admin/welcome#index", :as => "admin"
  match 'request_authsub_authorization' => "admin/welcome#request_authsub_authorization", :as => "admin"

  match '/auth/:provider/callback' => 'authentication#create'
  match '/auth/failure' => 'authentication#failure'

  match 'login' => 'session#new', :as => 'login'
  match 'logout' => 'session#destroy', :as => 'logout'
  match 'activate/:activation_code' => 'session#activate', :as => 'activate'

  match 'enewsletter' => 'static#enewsletter'
  match 'blog' => 'static#blog'
  match 'GeneralDynamics' => 'static#general_dynamics'
  match 'UnisysDescriptions' => 'static#unisys_descriptions'
  match 'BNSF-hot-job' => 'static#bnsf_hot_job'

  match 'static/download_docx/*path' => 'static#download_docx'
  match 'static/employer/*path' => 'static#index'
  match 'static/*path' => 'static#index'
  
  match ':controller/:action.:format'
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'
end

app/views/shared/_book_sponsors.html.erb
<div id="book-sponsors"  style="width:300px; margin-top:12px; padding-bottom:15px;">

  <div style="text-align: center; padding-top:10px;">
    <h2 style="margin:0px; padding:0px;"><%= link_to "Meet our Book Sponsors", welcome_path, :style=>"color:#FFF; text-decoration: none;" %></h2>
  </div>
  <div style="border:1px solid #555; background:#FFF; color:#000; font-weight:bold; font-size:120%; padding:5px 0px 10px 10px; margin:15px 35px 0px 35px;">
    <ul style="font-size:90%; line-height:2em; list-style-type:disc; list-style-position:inside;">
      <li>Lockheed</li>
      <li>Boeing</li>
      <li>Northon Grupman</li>
    </ul>
  </div>
  &nbsp;

</div>

app/views/shared/_cgo_book_sponsor.html.erb
<div style="margin-top: 20px">
  <%= link_to "http://www.corporategray.com/cgo/cgmediakit.pdf", :style => "color: blue" do %>
      <div style="width: 280px; height: 250px">
        <%= image_tag "CGS_book_cover_2013.png", :style => "border: 1px solid #4c4c4c; float:left;  height: 150px"  %>
        <div style="padding-top: 15px ; margin-left: 110px; font-size: 1.1em; font-weight: bold">
          See the all-inclusive print, job fairs, and online military recruitment services included in the Corporate Gray Book Sponsor Package!
        </div>
      </div>
  <% end %>
</div>

app/views/shared/_compact_jobfair_calendar.html.erb
<% jobfairs = Jobfair.all_upcoming %>

<div class="feature-title">Upcoming Job Fairs <%= "#{Time.now.year} - #{Time.now.year + 1}" %></div>
<div id="compact_jobfair_calendar">
<% if jobfairs %>

  <ul>
  <% jobfairs.each do |jobfair| %>
    <li>
      <div style="width: 85px"><%= link_to jobfair.date.to_s(:human), jobfair_path(jobfair.id) -%></div>
      <div style="margin-left: 5px;"><%=jobfair.city%></div>
      <div class="right">
      <% if current_user %>
        <% if !current_user.registered?(jobfair) %>
          <% if current_user.is_a?(Recruiter)  %>
            <%= link_to "register", jobfair.external_registration_url.to_s.strip.blank? ? new_jobfair_registration_path(jobfair.id) : jobfair.external_registration_url, :class=> jobfair.external_registration_url.to_s.strip.blank? ? "action_link" : "external" %>
          <% else %>
            <% if jobfair.category == 'military_officer' && (!Constants::TYPE_OF_APPLICANT.select {|x| ['O', 'W'].include?(x[:label][0,1])}.collect {|y| y[:id]}.include?(current_user.type_of_applicant))  %>
              Officers Only 
            <% else %>
              <%= link_to "register", jobfair.applicant_external_registration_url.to_s.strip.blank? ? new_jobfair_registration_path(jobfair.id) : jobfair.applicant_external_registration_url, :class => jobfair.applicant_external_registration_url.to_s.strip.blank? ? "action_link" : "external" -%>
            <% end %>
          <% end %>
        <% else %>
          <span style="color:green; font-style:italic">registered</span>
        <% end %>
      <% else %>
        <span style="color:green; font-style:italic"><%= link_to "please login", new_session_path -%></span>
      <% end %>

      </div>
    </li>
  <% end %>
  </ul>

<% end %>
</div>


<style>

  #compact_jobfair_calendar {
    height: 180px;
    overflow: scroll;
    min-height: 180px;
    border-bottom: 1px solid #AAA;
    border-left: 1px solid #AAA;
    border-right: 1px solid #AAA;
  }
  
  #compact_jobfair_calendar ul {
    clear: both; 
  }

  #compact_jobfair_calendar li {
    padding: 4px;
    line-height: 1.2em;
    height: 1.1em;
    display: block;
    float: none;
    clear: both;
    list-style: none;
  }

  #compact_jobfair_calendar div {
    float: left; 
  }

  #compact_jobfair_calendar div.right {
    float: right;
  }

</style>

app/views/shared/_featured_jobfair.html.erb
<style> 
  .large {
    font-size: 1.2em;
  }

  .x-large {
    font-size: 1.4em;
  }

  .bold {
    font-weight: bold;
  }

  .red {
    color: #BD0000;
  }

</style> 

<% jobfair = Jobfair.first_upcoming %>

<% if jobfair %>

<% # Determine the right tagline based on the jobfair's category
   (tagline = "Only for those job seekers with an active or current security clearance at Secret or above") if jobfair.category == "security_clearance"
   (tagline = "") if jobfair.category == "military_friendly"
   (tagline = "Only for separating Junior Military Officers at the grade of O-1 to O-3.  Military ID cards will be checked at registration.") if jobfair.category == "junior_officer"
%>

<div id="featured_jobfair" style="height: 260px;">
  <div class="large bold">
    <p><%= "Join us #{jobfair.date.to_s(:human_no_year)}" -%></p>
    <p><%= "#{jobfair.location} (#{jobfair.city})" -%></p>
  </div>

  <br/>
  <p class="large bold red">
    <%= link_to "Healthcare Job Fair", jobfair_path(340) %>
  </p>
  <p class="bottomlinks" style="margin-top: 5px">
    <%= link_to "View Attending Employers", jobfair_path(340) -%>
  </p>
  <p style="font-size: 18px; margin-top:10px; margin-bottom: 10px;"> & </p>
  <p class="large bold red">
    <%= link_to "Security Clearance", jobfair_path(jobfair.id) %>
    <br/>
    <%= link_to "Job Fair", jobfair_path(jobfair.id) %>
  </p>
  <p class="bottomLinks" style="margin-top:5px">
    <%= link_to "View Attending Employers", jobfair_path(jobfair.id) -%>
  </p>

</div>

<% end %>

<style>

  #featured_jobfair {
    font-family: Georgia;
    font-size: 1.1em;

    background: #EFEFEF; 
    text-align: center;

    padding: 10px 0;
  }

  #featured_jobfair .bottomLinks {
    margin-top: 20px;
  }

  #featured_jobfair a {
    color: inherit;
  }

</style>

app/views/shared/_jobfair_calendar.html.erb
<% jobfairs = Jobfair.all_upcoming %>
<% if jobfairs then %>
<div id="jobfair-calendar" class="portlet" style="border: 2px solid #FFF; border-bottom: 0px;">
  <div class="phead" style="padding-top: 5px; padding-bottom: 5px; font-size: 116%">
    Job Fair Calendar <%= "#{Time.now.year} - #{Time.now.year + 1}" %> 
  </div>
  <div class="pbody">
    <table id="jobfair-calendar-blotter">
      <thead>
	<tr>
	  <th width="17%">Date</th>
		<th width="8%">Type</th>
	  <th width="38%">Title</th>
	  <th width="20%">City</th>
		<% if (current_user && current_user.has_role?(:recruiter)) || @display_fees %>
						<th width="9%">Fee</th>
		<% end %>
	  <th>Status</th>
	</tr>
      </thead>
      <tbody>
	<% jobfairs.each do |jobfair| %>
	  <tr>
	    <td>
	      <%= jobfair.date.to_s(:human) -%>
	    </td>

        <td>
          <% case jobfair.category 
              when "military_friendly" %>
                MF 
          <% when "virtual" %>
                VI 
          <% when "military_officer" %>
                MO 
          <% when "healthcare" %>
                HC
          <% else  %>
                SC  
          <% end %>
        </td>

        <td>
          <%= link_to jobfair.category.titleize + " Job Fair", jobfair_path(jobfair.id) -%>
        </td>

        <td>
          <%= jobfair.city -%>
        </td>

        <% if (current_user && current_user.has_role?(:recruiter)) || controller.request.fullpath.match(/employers\/job_fairs/) %>
            <td><%= number_to_currency(jobfair.fees, :precision => 0) -%></td>
        <% end %>

	    <td>
		  <% if current_user %>
		    <% if !current_user.registered?(jobfair) %>
              <% if current_user.is_a?(Recruiter)  %>
                <%= link_to "register", jobfair.external_registration_url.to_s.strip.blank? ? new_jobfair_registration_path(jobfair.id) : jobfair.external_registration_url, :class=> jobfair.external_registration_url.to_s.strip.blank? ? "action_link" : "external" %>
              <% else %>
                <% if jobfair.category == 'military_officer' && (!Constants::TYPE_OF_APPLICANT.select {|x| ['O', 'W'].include?(x[:label][0,1])}.collect {|y| y[:id]}.include?(current_user.type_of_applicant))  %>
                 Officers Only 
                <% else %>
                  <%= link_to "register", jobfair.applicant_external_registration_url.to_s.strip.blank? ? new_jobfair_registration_path(jobfair.id) : jobfair.applicant_external_registration_url, :class => jobfair.applicant_external_registration_url.to_s.strip.blank? ? "action_link" : "external" -%>
                <% end %>
              <% end %>
            <% else %>
              <span style="color:green; font-style:italic">registered</span>
            <% end %>
          <% else %>
            <span style="color:green; font-style:italic"><%= link_to "please login", new_session_path -%></span>
          <% end %>
	    </td>
	  </tr>
	<% end %>
      </tbody>
    </table>
  </div>
  <div style="text-align: left; padding-top: 15px; padding-bottom: 5px; margin-left: 3px; font-size: 0.9em; color: #444;">
			MF: Especially for transitioning and former military personnel. Civilians welcome.<br/>
			SC: Only for those job seekers with a Secret or higher security clearance.<br/>
            VI: Virtual Career Fair.<br/>
            MO: Military Officer only.<br/>
            HC: Healthcare.
	 </div>
</div>
<% end %>

<style>
  #jobfair-calendar-blotter {
    width: 100%; 
    text-align: left; 
  }
  
  #jobfair-calendar-blotter th {
    font-weight: bold; 
  }
  
  #jobfair-calendar-blotter td, #jobfair-calendar-blotter th {
    padding-left: 3px; 
    padding-top: 4px;
    padding-bottom: 4px;
    border-bottom: 1px solid #ccc;
  }
</style>

app/views/shared/_linkedin_well.html.erb
<div class="well" id="linkedin-pair-well" >
  <h2 style="margin-top:0px">Enhance Your Searches</h2>
  <p style="color:#4c4c4c; line-height: 1.7em; letter-spacing: 1px;">
    You can enhance your job search experience by authorizing CGO to access your linkedIn profile.<br/>
    We will show you who, &mdash; among your connections, work at the companies you research for jobs.
  </p>
  <br/>
  <div style="text-align: center; ">
    <a id="auth" href='/auth/linked_in' class="btn btn-primary" style="text-decoration:none !important;">Authorize LinkedIn Access</a>
    <p id="auth-linkedin-success" style="display: none; background:#67E667; color:#104810; padding:6px; border-radius:4px;">Success, Your account is now paired with LinkedIn</p>
  </div>
</div>

app/views/shared/_login_box.html.erb
<div class="round-corners dark-highlight" >
  <div style="postion: relative; width: 300px;">
    <h2 style="margin: 0px 5px 5px 5px;text-align:center; padding-bottom:5px;">
      <%= user_type == :employer ? "Employer Login" : "Job Seeker Login" -%>
    </h2>

    <%= render :partial => "/session/new.html.erb" %>

    <div style="text-align:right; border-top:1px solid #CCC; padding:6px 10px 2px 3px; margin:5px 5px 0px 5px;">
      <% if user_type != :employer %>
        <%= link_to "Not a member? Create an account", new_applicant_path, :class=>"action_link", :style=>"color:#FFF;" -%>
      <% else %>
        <%= link_to "Not a member? Create an account", new_employer_path, :class=>"action_link", :style=>"color:#FFF;" -%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_multi_jobfair_discount.html.erb
<div style="text-align: center; background: whitesmoke; border: 2px solid black; padding: 1em;">
  <h2 style="margin-top:0; color: #BD0000;">Take Advantage <br/> of our Multi Job Fair Discount</h2>
  <p>Download this <%= link_to "form", "http://www.corporategray.com/cgo/CGO_multi_jobfair_contract.xlsx" %> for more information</p>
</div>

app/views/shared/_new_account_greeting.html.erb
<% content_for :page_title do %>
Welcome to Corporate Gray Online
<% end %>

<p><b>Thank you for registering on Corporate Gray Online</b></p><br/>
<p>You can now login to access member-only services.
</p>
<br/>

<p>The Corporate Gray Online Team</p>

app/views/shared/_new_site_feedback.html.erb
<% if !current_user.nil? %>
<div style="margin-bottom: 25px;margin-top: 5px;"><div class="round-corners light-highlight">
				<div style="padding: 5px; font-weight: bold; text-align: center;font-size: 115%">
                  Please give us Feedback. click <%= link_to "here", "mailto:#{UserMailer.admin_email}?subject=New%20Site%20Feedback" %>
				</div>
		</div>
</div>
<% end %>

app/views/shared/_quick_search_box.html.erb
<!-- ############# DEPRECATED ############## -->
<% 
 if (!current_user.nil? && (current_user.has_role?(:employer_admin) || current_user.has_role?(:recruiter))) ||
    (current_user.nil? && (controller.controller_name == "employer")) || 
    (/employer/i =~ request.env['REQUEST_URI'] || /contact_info/i =~ request.env['REQUEST_URI'])

   path = quick_search_resumes_path(:format => :html)
   search_title = "Search Resumes:"
 else
   path = search_jobs_path(:format => :html)
   search_title = "Search Jobs:"
 end
%>
<%= form_for :quick_search, :url => path, :html => {:method => :get, :id => "quick-job-search-form"} do |f| %> 
  <div style="font-size: 1.4em; color:#FFF; margin-top: 17px;"><%= search_title -%></div>
  <div>
    <label>Keywords</label>
    <input type="text" name="q[keyword]" id="keyword" style="padding-left:3px;"/>
  </div>
  <div class="button-bar" style="margin-top: 18px">
    <%= image_submit_tag "/images/buttons/bt_search_green.gif", :style=>"width:auto; border:none; outline: none;" -%>
  </div>
<% end %>

app/views/shared/_quick_search_form.html.erb
<% unless (!current_user.nil? && (current_user.has_role?(:employer_admin) || current_user.has_role?(:recruiter))) %>

    <% 
    if(current_user.nil? && (controller.controller_name == "employer")) || (/employer/i =~ request.env['REQUEST_URI'] || /contact_info/i =~ request.env['REQUEST_URI'])
      path = guest_search_resumes_path(:format => :html)
      search_title = "Search Resumes:"
    else
      path = search_jobs_path(:format => :html)
      search_title = "Search Jobs:"
    end
    %>

    <div style="width: 280px">
      <%= form_for :quick_search, :url => path, :html => {:method => :get, :id => "quick-job-search-form"} do |f| %> 
        <div style="font-size: 1.6em; color:#FFF; margin-bottom: 5px;"><%= search_title -%></div>
        <%= submit_tag "Go", :style => " float: right;  color:#859900; width:4em; padding:4px 10px; margin-right: 10px; margin-left:0.5em; border:2px solid #268bd2; border-radius:4px; background:#FFF; font-weight:bold;" %>
        <div style="padding:0;">
          <input type="text" name="q[keyword]" id="keyword" style="margin:0px; width:11em; border:2px solid #268bd2; border-radius: 4px; padding:5px; font-size:1.2em; font-weight:bold;"/>
          <div style="font-size: 0.9em; font-style: italic; margin-top: 4px; color:#ccc;">Enter keyword(s)</div>
        </div>
      <% end %>
    </div>

<% end %>

app/views/shared/_right_ads.html.erb
<table style="width:300px; margin-top: 20px;" cellpadding="2">
		<tr>
    <td>
      <%= link_to image_tag("ads/dia_ad_144x100.jpg"), "http://www.dia.mil", :class => "popup" -%>
    </td>

    <td style="text-align:right">
      <%= link_to image_tag("ads/dcma_ad_144x100.jpg"), "http://www.dcma.mil", :class => "popup" -%>
    </td>
		</tr>
</table>

app/views/shared/_sign_up_promotion.html.erb
<% if user_type != :employer %>

   <div class="dark-highlight" style="border: 3px solid #E11F27; width: 294px">

     <div style="padding: 5px;padding-left: 1em; line-height: 1.65em; display:block; position: relative; text-align: left; font-size: 1.1em">
          <%= link_to  image_tag("join_for_free.gif", :style=>"z-index: 2147483646; position: absolute; left: -50px; top: -30px; margin-left: 1em;"), new_applicant_path %>
          <div style="padding-left: 67px;">
            Get instant access to a host of career building resources: 
            increase your visibility to 
          </div> 
           potential employers, search 1000's of jobs, and pre-register
          for our military-focused Job Fairs. 
          <div style="margin-top: 0.75em"><%=link_to "Click HERE to Get Your FREE Account", new_applicant_path , :style => "color: #E11F27" %></div>
    </div>

  </div>

  <div style="float:none; clear:both; height: 30px">&nbsp;</div>


<% else %>

   <div class="dark-highlight" style="border: 3px solid #E11F27; width: 294px">

     <div style="padding: 5px;padding-left: 1em; line-height: 1.65em; display:block; position: relative; text-align: left; font-size: 1.1em">
          <%= link_to  image_tag("join_for_free.gif", :style=>"z-index: 2147483646; position: absolute; left: -50px; top: -30px; margin-left: 1em;"), new_employer_path %>
          <div style="padding-left: 67px;">
            Create a FREE employer account as a first step to connect 
            with transitioning and 
          </div> 
          former military personnel using our print, job fair, and 
          online military recruitment services.
          <div style="margin-top: 0.75em"><%=link_to "Click HERE to Get Your FREE Account", new_employer_path , :style => "color: #E11F27" %></div>
    </div>

  </div>

  <div style="float:none; clear:both; height: 30px">&nbsp;</div>

<% end %>