config/routes.rb
Cgray::Application.routes.draw do

  resources :sitemap do 
    collection do 
      get :basic
      get :jobfairs
      get :jobs
      get :employers
      get :static
    end
  end

  resources :users, :controller => "user"
  
  resources :sessions, :controller => 'session' do
    collection do
      get :password_reminder 
    end
  end

  resources :authentications, :controller => 'authentication' do
    collection do
      post :link
    end
  end

  resources :applicants, :controller=> 'applicant' do 

    collection do
      get  :deactivate
      post :process_deactivation 
    end

    member do 
      post :apply 
      post :enable_social_login
      get  :photo
    end
  end

  resources :connections do
    member do
      get :photo
    end
  end

  resources :employers, :controller => 'employer' do

    collection do
      get :job_fairs 
      get :services
    end

    member  do  
      get :public_profile 
    end

    resources :recruiters, :controller => 'recruiter' do 
      member do
        get :current_status 
        get :dashboard 
      end
    end

    resources :ofccp do 
      collection do
        post :download_to_excel
        post :download 
      end
    end

  end

  resources :jobs do 
    
    collection do 
      get :search 
      get :quick_search 
      post :auto_complete_for_employer_name 
    end

	member do 
      get :repost 
      get :apply 
      get :apply_notify
      get :add_to_inbox
      get :remove_from_inbox 
      get :public_profile 
    end

  end

  resources :resumes do 

    collection do 
      get :search
      get :quick_search 
      get :guest_search
      get :guest_index
    end

	member do 
      get :add_to_inbox 
      get :remove_from_inbox 
      get :print 
     post :forward 
      get :download 
      get :attachment 
    end
  end

  resources :positions do
    member do
      post :validate
    end
  end

  resources :educations do
    member do
      post :validate
    end
  end

  resources :jobfairs, :controller => "jobfair" do 
    member do 
      get :registered_employers 
    end

	   resources :registrations
  end

  resources :messages

  resources :registrations do
    collection do 
      get  :new_from_affiliate 
      post :post_from_affiliate 
    end
  end

  
  namespace :admin do 

    resources :jobfairs

	   resources :registrations do
      member do 
        get :enable_search 
      end
    end

    resources :employers do
      member do 
        post :administrator_name 
      end

      resources :recruiters do 
        collection do 
          get :download_to_excel 
        end
      end

      resources :jobs
    end

    resources :recruiters do 
      collection do 
        post :auto_complete_for_employer_name 
        post :update_employer 
        get  :edit_employer
      end
    end

    resources :applicants do 
      collection do 
        post :upload
        post :download_to_excel 
      end

    end

    resources :resumes do 
      collection do
        get :search 
      end

      member do 
        get :download 
        get :attachment 
       post :forward
      end

    end

    resources :users do 
      member do
        get :skip_email_verification 
      end
    end

	   resources :ofccp do
      collection do 
        post :download_to_excel 
      end
    end

  end 
  
  
  root :to => 'welcome#index'
  match 'welcome' => 'welcome#index', :as => 'welcome' 

  match 'admin' => "admin/welcome#index", :as => "admin"
  match 'request_authsub_authorization' => "admin/welcome#request_authsub_authorization", :as => "admin"

  match '/auth/:provider/callback' => 'authentication#create'
  match '/auth/failure' => 'authentication#failure'

  match 'login' => 'session#new', :as => 'login'
  match 'logout' => 'session#destroy', :as => 'logout'
  match 'activate/:activation_code' => 'session#activate', :as => 'activate'

  match 'enewsletter' => 'static#enewsletter'
  match 'blog' => 'static#blog'
  match 'GeneralDynamics' => 'static#general_dynamics'
  match 'UnisysDescriptions' => 'static#unisys_descriptions'
  match 'BNSF-hot-job' => 'static#bnsf_hot_job'

  match 'static/download_docx/*path' => 'static#download_docx'
  match 'static/employer/*path' => 'static#index'
  match 'static/*path' => 'static#index'
  
  match ':controller/:action.:format'
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'
end

app/models/recruiter.rb
class Recruiter < User

  belongs_to :employer
  has_many :jobs, :dependent => :destroy
  has_many :recruiter_stats, :dependent => :destroy

  validates_presence_of :employer_id
  # validates_presence_of :sales_person_id if @current_user && (@current_user.has_role?('admin') || @current_user.has_role?('sales_rep'))

  def register_for(jobfair, options = {})
    # Attendant should always be the"employer_admin" fallback to 
    # current_user if no administrator (until old accounts are 
    # fixed and folded into one)
    administrator = employer.administrator || self
    super(jobfair, options.merge({:attendant => administrator}))
  end

  def registered?(jobfair)
    employer.registrations.collect {|registration| registration.jobfair}.any? {|jf| jf.id == jobfair.id}
  end
  
  def increment_login_count_stat
    stat = get_current_date_stat_record
    stat.login_count = stat.login_count + 1
    stat.save
  end

  def increment_resume_views_stat
    stat = get_current_date_stat_record
    stat.resume_views = stat.resume_views + 1
    stat.save
  end

  def increment_resume_searches_stat
    stat = get_current_date_stat_record
    stat.resume_searches = stat.resume_searches + 1
    stat.save
  end

  private

  def get_current_date_stat_record
    today = Date.today
    stat = self.recruiter_stats.where(["MONTH(created_at) = ? AND YEAR(created_at) = ?", today.month, today.year]).first()
    if !stat
      stat = RecruiterStat.new({:recruiter_id => self.id}); 
    end

    return stat
  end

end

app/controllers/admin/recruiters_controller.rb
class Admin::RecruitersController < ApplicationController
  layout "admin/layouts/application"

  protect_from_forgery :except => ["auto_complete_for_employer_name", "index_by_employer"]

   def index

     if !params[:recruiter_employer].to_s.blank?
       results = Recruiter.find :all, 
          :include => [:employer], 
          :conditions => ["roles = 'recruiter' AND employers.name like ?", "#{params[:recruiter_employer]}%" ] , 
          :order => "last_name, first_name ASC"

     elsif !params[:recruiter_last_name].to_s.blank?
       results = Recruiter.find :all, 
          :include => [:employer],
          :conditions => ["last_name like ?", "#{params[:recruiter_last_name]}%"],
          :order => "last_name, first_name ASC"
     else
       results = []
     end

     @recruiters = results.select {|r| !r.has_role?("employer_admin") }

     respond_to do |format|
       format.xhr { render :layout => false, :template => "admin/recruiters/index.html.erb" }
     end
     
   end

   def edit_employer
   end

   def update_employer
     new_employer = Employer.find params[:new_employer_id]
     params[:recruiters].each do |recruiter_id|

       recruiter = Recruiter.find(recruiter_id)

       recruiter.employer.registrations.each do |registration|
         new_employer.registrations << registration unless new_employer.registrations.any? { |r| r.jobfair_id == registration.jobfair_id }
       end

       new_employer.recruiters <<  recruiter
     end
  
     redirect_to :action => :edit_employer

   end

   def auto_complete_for_employer_name
     results = Employer.find :all, :include => ["recruiters"], :conditions => ["name like ?", params[:employer][:name]+'%' ]
     @employers = results.select {|e| e.recruiters.any? {|r| r.has_role?("employer_admin")} }
     render :layout => false
   end

   def show
    @employer = Employer.find params[:employer_id]
    @recruiter = @employer.recruiters.find params[:id]
   end


  def new

	   @employer = Employer.find params[:employer_id]

    if @employer.recruiters.size >= @employer.max_recruiters
      logger.info("#{@employer.name} has reached the maximum number of recruiters allowed ")
      flash[:notice]="You have reached the maximum number of recruiters allowed for #{@employer.name}"
      redirect_to admin_employer_path(@employer.id)
    end

    @recruiter = Recruiter.new
    @address =  Address.new(:label => 'primary')
  end


  def create
	   @employer = Employer.find params[:employer_id]

    @recruiter = Recruiter.new(params[:recruiter])
    @recruiter.activated_at = Time.now					# Don't require email activation code for recruiters created through the back-end
    @address = Address.new(params[:address])
    @employer.recruiters << @recruiter

    Recruiter.transaction do
      @recruiter.save!
      @recruiter.addresses << @address
    end

    flash[:notice] = "Your changes have been saved"
    redirect_to admin_employer_path(@employer.id)

  rescue ActiveRecord::ActiveRecordError
    @address.valid?
    render :action => "new"
  end


  def edit
    @employer = Employer.find params[:employer_id]
    @recruiter = @employer.recruiters.find(params[:id])
    @address = @recruiter.addresses[:primary] || Address.new(:label => "primary")
  end


  def update
    @employer = Employer.find params[:employer_id]
    @recruiter = @employer.recruiters.find(params[:id])

    Recruiter.transaction do
	    @recruiter.update_or_create_address(params[:address].merge({:label => "primary"}))
      @recruiter.update_attributes!(params[:recruiter])
    end

    flash[:notice] = "Your changes to #{@recruiter.name}\' profile have been saved"
    redirect_to admin_employer_path(:id => @employer.id)

  rescue ActiveRecord::ActiveRecordError => e
    @recruiter.valid?
    flash[:error] = e.to_s
    render :action => "edit"
  end

  def download_to_excel

			 @employer = Employer.find params[:employer_id]
			 @recruiters = @employer.recruiters

			 headers['Content-Type'] = "application/vnd.ms-excel"
       headers['Content-Disposition'] = "attachment; filename=#{@employer.id}_recruiters_#{Time.now.to_formatted_s(:mm_dd_yyyy)}.xls"

			 render :layout => false
	end

end

app/controllers/recruiter_controller.rb
require "constants.rb"

class RecruiterController < ApplicationController
  
  before_filter :login_required
  require_role	:employer_admin, :only => ["new", "create", "destroy"]
  
  def index
    @recruiters = current_employer.recruiters.find(:all, :conditions => ["id != ?", current_user.id], :order => "first_name, last_name DESC")
  end

  def dashboard
    @messages_inbox = current_user.messages.find(:all, :limit => 25)
    @resumes_inbox = current_user.inbox_entries(:limit => Constants::MAX_INBOX_SIZE).sort_by { |entry| entry.created_at.to_date }
    inbox_applicants = current_user.inbox_entries.collect {|entry| entry.resource ? entry.resource.applicant : nil}.compact
    @applicants = WillPaginate::Collection.create(1, 25, inbox_applicants.size) do |pager|
       pager.replace(inbox_applicants)
    end
    
    @registrations = current_user.registrations.select {|registration| registration.jobfair.date > Time.now.to_date}
  end

  def show
    @recruiter = current_employer.recruiters.find(params[:id])
  end

  def new
    
    if current_employer.recruiters.size >= current_employer.max_recruiters
      logger.info("#{current_employer.name} has reached the maximum number of recruiters allowed ")
      flash[:notice]="You have reached the maximum number of recruiters allowed for your organization"
      redirect_to employer_recruiters_path(current_employer.id) 
    end
    
    @recruiter = Recruiter.new
    @address =  Address.new(:label => 'primary')
  end

  
  def create
    @recruiter = Recruiter.new(params[:recruiter])

    # Disable email verification per Carl's request.
    #@recruiter.make_activation_code
    @recruiter.activation_code = nil
    @recruiter.activated_at = Time.now
    @recruiter.status = "active"

    @recruiter.add_role("recruiter")
    @address = Address.new(params[:address])
    current_employer.recruiters << @recruiter

    Recruiter.transaction do
      @recruiter.save!
      @recruiter.addresses << @address
    end
    
    flash[:notice] = "Your changes have been saved"
    redirect_to employer_recruiters_path(current_employer.id)
    
  rescue ActiveRecord::ActiveRecordError
    @address.valid?
    render :action => "new"
  end
  
  def edit
    @recruiter = current_employer.recruiters.find(params[:id])
    @address = @recruiter.addresses[:primary] || Address.new(:label => "primary")
  end
  
  def update
    @recruiter = current_employer.recruiters.find(params[:id])
    
    Recruiter.transaction do
      @recruiter.update_or_create_address(params[:address])
      @recruiter.update_attributes!(params[:recruiter])
    end
    
    flash[:notice] = "Your changes to #{@recruiter.name}\' profile have been saved"
    redirect_to(employer_recruiter_path(:employer_id => current_employer.id, :id => current_user.id))  and return
    
  rescue ActiveRecord::ActiveRecordError => e
    @recruiter.valid?
    flash[:error] = e.to_s
    render :action => "edit"
  end
  
  def destroy
    current_user.employer.recruiters.find(params[:id]).destroy
    redirect_to employer_recruiters_path(:id => current_user.employer.id)
  end
  
  # AJAX update of recruiter's status
  def current_status
    @recruiter = current_employer.recruiters.find(params[:id])
    @recruiter.update_attribute(:status, params[:s])
    render :nothing => true
  end


  
end

app/helpers/admin/recruiters_helper.rb
module Admin::RecruitersHelper
end

app/helpers/recruiter_helper.rb
module RecruiterHelper
end

app/views/admin/recruiters/_form.html.erb
<%= error_handling_fields_for @recruiter do |user_form| -%> 
	<%= user_form.check_box "status", {:label => "&nbsp;Status (Check to Activate User)" }, "active", "inactive" -%>
	<%= render :partial => "user/form.html.erb", :object => user_form %>
<% end %>

<fieldset>
	<legend>Contact Information</legend>

	<%= error_handling_fields_for @address do |a_form| -%>
		<%= render :partial => "/address/address.html.erb" -%>
	<% end %>
</fieldset

app/views/admin/recruiters/auto_complete_for_employer_name.xhr.erb
<ul style="cursor:pointer">
  <% @employers.each do |employer| %>
    <li id='<%="emp-#{employer.id}"%>'><%="(#{employer.id}) #{employer.name}" -%></li>
  <% end %>
</ul>

app/views/admin/recruiters/edit.html.erb
<% content_for :page_title do %>
	Edit <%= @recruiter.name -%>
<% end %>

<% content_for :page_header_links do %>
	<%= link_to "Cancel", admin_employer_path(@employer.id) %>
<% end %>

<%= error_messages_for @recruiter, @address %>

<% error_handling_form_for @recruiter, 
			   :url => admin_employer_recruiter_path(@employer.id, @recruiter.id),
			   :html => {:id => "recruiterform"} do |f| %>

	<%= render :partial => "form", :object => f -%>
	
	<div class="button-bar">
		<a class="button" href="#" onclick="$('recruiterform').submit(); return false;"><span>save</span></a>
		<div>or <%= link_to "Cancel", admin_employer_path(:id => @employer.id), :class=>"cancel"%></div>
	</div>
<% end %>

app/views/admin/recruiters/edit_employer.html.erb
<% content_for :page_title do %>
Edit Recruiters Employer Admin
<% end %>

<script>

  var employerId = -1; 

  function employerNameUpdated(element, value) {
    
    selectedId = value.id.split('-')[1];
    if(selectedId != -1) {
      window.employerId = selectedId;
      new Ajax.Updater('employer-admin-name', '/admin/employers/' + employerId + '/administrator_name.xhr', {
          onComplete: function(response) {
            new Effect.Highlight('employer-admin-name');
          }
      });
    }

  }

</script>

<div>
  <div style="font-size: 1.3em; font-weight: bold;  margin-bottom: 15px;">Select Employer Admin</div>
  <div style="font-weight:bold; margin-bottom: 5px">Company Name</div>
  <%= text_field_with_auto_complete :employer, :name, {}, { :indicator => "employer-name-indicator", :after_update_element => "employerNameUpdated" } %>
  <span id="employer-name-indicator" style="display:none; margin-left: 3px; margin-right: 12px;"><%= image_tag "dots.gif" -%></span>
  <div id="employer-admin-name" style="margin-right: 2em; float: right; clear: none; width:22em; padding: 4px; border: 1px solid #CCC; font-weight: bold;">
    Employer Admin 
  </div>
</div>


<div style="margin-top: 30px; border-top: 1px solid #CCC; padding-top: 5px;">

  <div style="font-size: 1.3em; font-weight: bold; margin-top: 3px; margin-bottom: 5px;">Search Recruiters</div>

  <div style="margin-top: 20px">

    <div style="float:left; clear: none;" >
      <div style="font-weight: bold; ">By Employer</div>
      <input id="recruiter_employer" name="recruiter_employer" style="width: 15em;"/>
    </div>

    <div style="float:left; clear: none; margin-left: 10px;" >
      <div style="font-weight: bold; ">By Last Name</div>
      <input id="recruiter_last_name" name="recruiter_last_name" style="width: 15em"/>
    </div>

  </div>

  <div style="float:left; clear: both; margin-top: 16px; margin-left: 0px; ">
    <%= link_to("Search", "#", :onclick => "javascript: searchRecruiters();", :id => "searchbutton",  :class => "xbutton blue") %>
    <span id="recruiter-search-indicator" style="display: none;"><%= image_tag "dots.gif", :style => "margin-left: 3px; margin-top: 9px;" -%></span>
  </div>

  <script>
    function searchRecruiters() {
      new Ajax.Updater("recruiters", "/admin/employers/"+window.employerId+"/recruiters.xhr", {
          method: "GET",
          parameters: { recruiter_employer : $('recruiter_employer').value, recruiter_last_name : $('recruiter_last_name').value },
          onCreate: function(request, response) {
            $('recruiter-search-indicator').show();
          },

          onComplete: function(request, response) {
            $('recruiter-search-indicator').hide();
          }
      }); 
    }
  </script>

</div>

<div style="float:none; clear:both; height:1px">&nbsp;</div>

<div id="recruiters"></div>


<style>
  .recruiters td {
    border-bottom: 1px solid #DDD;
    padding-top: 8px;
  }

  .recruiters th {
    font-weight: bold;
    color: #DDD; 
    background: #4c4c4c;
  }
</style>



<script>

var EmployerNameBehaviors = Behavior.create(); 
Object.extend(EmployerNameBehaviors.prototype, {
    onchange: function() {
      employerId = -1;
      $('searchbutton').disabled=true;
    },

    onfocus: function() { 
      $('employer_name').setStyle({textDecoration: 'none'});
    },

    onblur: function() {
      if(employerId == -1) {
        $('employer_name').setStyle({textDecoration: 'line-through'});
      }
    }

});

Event.addBehavior({
    '#employer_name' : EmployerNameBehaviors()
});


</script>

app/views/admin/recruiters/index.html.erb
<%= form_tag update_employer_admin_recruiters_path, :id => "recruitersupdate" do %>
  <%= hidden_field_tag :new_employer_id, nil -%>

  <table class="recruiter-blotter" style="width: 100%; margin-top: 20px; border-bottom: 2px solid #000;">
    <thead>
      <tr>
        <th style="font-weight: bold; border-bottom: 2px solid #000;"><%= link_to_function "All", "$$('#recruiters-items input').each(function(tag, index) {tag.checked=true;})" -%>&nbsp;|&nbsp;<%= link_to_function "None","$$('#recruiters-items input').each(function(tag, index) {tag.checked=false;})" -%></th>
        <th style="font-weight: bold; border-bottom: 2px solid #000;">Name (username)</th>
        <th style="font-weight: bold; border-bottom: 2px solid #000;">Current Employer</th>
      </tr>
    </thead>
    <tbody id="recruiters-items">
    <% @recruiters.each do |recruiter| %>
      <tr>
        <td style="padding-top: 4px; padding-bottom: 4px; border-bottom: 1px solid #DDD;" width="12%"><input name="recruiters[]" type="checkbox" value="<%=recruiter.id.to_s-%>" style="width:auto;"/>
          <td style="padding-top: 4px; padding-bottom: 4px; border-bottom: 1px solid #DDD;<%=recruiter.status == 'inactive' ? 'font-style: italic; color: #6c6c6c;' : '' %>"><%= "#{recruiter.last_name}, #{recruiter.first_name} (#{recruiter.username})" -%></td>
        <td style="padding-top: 4px; padding-bottom: 4px; border-bottom: 1px solid #DDD;" width="45%"><%= "(#{recruiter.employer.id}) #{recruiter.employer.name}" -%></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div style="float:none; clear:both; height: 20px;">&nbsp;</div>
  <div class="button-bar">
    <a class="button" href="#" onclick="$('new_employer_id').value = window.employerId; $('recruitersupdate').submit(); return false;"><span>save</span></a>
    <div>or <%= link_to "Cancel", edit_employer_admin_recruiters_path, :class=>"cancel"%></div>
  </div>
<% end %>

app/views/admin/recruiters/new.html.erb
<% content_for :page_title do %>
  New Recruiter Registration
<% end %>

<% content_for :page_header_links do %>
  <%= link_to "Cancel", admin_employer_path(@employer.id) %>
<% end %>

<%= error_messages_for @recruiter, @address %>


<% error_handling_form_for @recruiter, :url => admin_employer_recruiters_path(:employer_id => @employer.id), :html => {:id => "recruiterform"} do |f| %>

  <%= render :partial => "form", :object => f -%>

  <div class="button-bar">
    <a class="button" href="#" onclick="$('recruiterform').submit(); return false;"><span>save</span></a>
    <div>or <%= link_to "Cancel", employer_recruiters_path(:employer_id => @employer.id), :class=>"cancel"%></div>
  </div>

<% end %>

app/views/admin/recruiters/show.html.erb
<%= content_for :page_title do %>
	<%= @recruiter.name -%>
<% end %>

<% content_for :page_header_links do %>
	<%= link_to "Edit", edit_admin_employer_recruiter_path(:employer_id => @employer.id, :id => @recruiter.id) -%>&nbsp;|&nbsp;
	<%= link_to "Delete", admin_employer_recruiter_path(:employer_id => @employer.id, :id => @recruiter.id), :method => :delete -%>&nbsp;|&nbsp;
	<%= link_to "New", new_admin_employer_recruiter_path(:employer_id => @employer.id) -%>&nbsp;|&nbsp;
	<%= link_to "View All", admin_employer_path(:id => @employer.id) -%>
<% end %>

<table class="show-model">
	<% unless @recruiter.active? %>
	<tr>
			<td class="label">Email Verified?</td>
			<td>
			<%= check_box :recruiter, :email_verified,
										:onclick => remote_function(:url => skip_email_verification_admin_user_path(@recruiter.id),
																								:method => "get",
																								:with => "'enable=yes'",
																								:loading => "$('indicator').show()",
																								:complete => "$('indicator').innerHtml('email verified, confirmation email sent')"),
										:style => "width: 0.8em; margin-right: 4px;",
										:checked => @recruiter.active?,
										:disabled => @recruiter.active?
			%>
			<span id="indicator" style="display:none;vertical-align:top;color:#BD0000;font-size:90%;"><%= image_tag "/images/dots.gif", :style=> "padding-top: 5px;" -%></span>
			</td>
	</tr>
	<% end %>

	<tr class="name"><td class="label">Name:</td><td><%= @recruiter.name -%></td></tr>
	<tr class="email"><td class="label">Email:</td><td><%= or_unspecified(@recruiter.email) %></td></tr>
	<tr class="usename"><td class='label'>Username:</td><td><%= @recruiter.username -%></td>
	<tr class="password"><td class="label">Password:</td><td><%= @recruiter.password -%></td></tr>
	<tr class="roles"><td class="label">Roles:</td><td><%= @recruiter.roles.gsub(/\s/, ", ").titleize -%></td></tr>
	<tr class="created_at"><td class="label">Created:</td><td><%= @recruiter.created_at -%></td></tr>
	<tr class="modified_at"><td class="label">Last Modified On:</td><td><%= @recruiter.updated_at -%></td></tr>
	<tr class="last_login_at"><td class="label">Last Login On:</td><td><%= @recruiter.last_login_at -%> (Count: <%=@recruiter.login_count -%>)</td></tr>
</table>


<% content_for :right do %>
			<div>
								<%= form_tag new_admin_registration_path, :id=>"registrationform", :method => :get do %>
												<%= hidden_field_tag :attendant_id, @recruiter.id -%>
												<label><b>New Registration for job fair:</b>
																				<%= select_tag :jobfair_id , 
																								options_for_select(Jobfair.find(:all, :order => 'date DESC').select { |x|
																													!@recruiter.registered?(x)
																								}.collect {|x| ["#{x.date.to_s(:short_with_year)} -- #{x.city}", x.id.to_s]}) %>
												</label>
								<% end %>
								<div class="button-bar" style="padding-top: 20px">
												<a class="button" onclick="$('registrationform').submit(); return false;" href="#"><span>Create ...</span></a>
								</div>

			</div>
<% end %>