config/routes.rb
Cgray::Application.routes.draw do

  resources :sitemap do 
    collection do 
      get :basic
      get :jobfairs
      get :jobs
      get :employers
      get :static
    end
  end

  resources :users, :controller => "user"
  
  resources :sessions, :controller => 'session' do
    collection do
      get :password_reminder 
    end
  end

  resources :authentications, :controller => 'authentication' do
    collection do
      post :link
    end
  end

  resources :applicants, :controller=> 'applicant' do 

    collection do
      get  :deactivate
      post :process_deactivation 
    end

    member do 
      post :apply 
      post :enable_social_login
      get  :photo
    end
  end

  resources :connections do
    member do
      get :photo
    end
  end

  resources :employers, :controller => 'employer' do

    collection do
      get :job_fairs 
      get :services
    end

    member  do  
      get :public_profile 
    end

    resources :recruiters, :controller => 'recruiter' do 
      member do
        get :current_status 
        get :dashboard 
      end
    end

    resources :ofccp do 
      collection do
        post :download_to_excel
        post :download 
      end
    end

  end

  resources :jobs do 
    
    collection do 
      get :search 
      get :quick_search 
      post :auto_complete_for_employer_name 
    end

	member do 
      get :repost 
      get :apply 
      get :apply_notify
      get :add_to_inbox
      get :remove_from_inbox 
      get :public_profile 
    end

  end

  resources :resumes do 

    collection do 
      get :search
      get :quick_search 
      get :guest_search
      get :guest_index
    end

	member do 
      get :add_to_inbox 
      get :remove_from_inbox 
      get :print 
     post :forward 
      get :download 
      get :attachment 
    end
  end

  resources :positions do
    member do
      post :validate
    end
  end

  resources :educations do
    member do
      post :validate
    end
  end

  resources :jobfairs, :controller => "jobfair" do 
    member do 
      get :registered_employers 
    end

	   resources :registrations
  end

  resources :messages

  resources :registrations do
    collection do 
      get  :new_from_affiliate 
      post :post_from_affiliate 
    end
  end

  
  namespace :admin do 

    resources :jobfairs

	   resources :registrations do
      member do 
        get :enable_search 
      end
    end

    resources :employers do
      member do 
        post :administrator_name 
      end

      resources :recruiters do 
        collection do 
          get :download_to_excel 
        end
      end

      resources :jobs
    end

    resources :recruiters do 
      collection do 
        post :auto_complete_for_employer_name 
        post :update_employer 
        get  :edit_employer
      end
    end

    resources :applicants do 
      collection do 
        post :upload
        post :download_to_excel 
      end

    end

    resources :resumes do 
      collection do
        get :search 
      end

      member do 
        get :download 
        get :attachment 
       post :forward
      end

    end

    resources :users do 
      member do
        get :skip_email_verification 
      end
    end

	   resources :ofccp do
      collection do 
        post :download_to_excel 
      end
    end

  end 
  
  
  root :to => 'welcome#index'
  match 'welcome' => 'welcome#index', :as => 'welcome' 

  match 'admin' => "admin/welcome#index", :as => "admin"
  match 'request_authsub_authorization' => "admin/welcome#request_authsub_authorization", :as => "admin"

  match '/auth/:provider/callback' => 'authentication#create'
  match '/auth/failure' => 'authentication#failure'

  match 'login' => 'session#new', :as => 'login'
  match 'logout' => 'session#destroy', :as => 'logout'
  match 'activate/:activation_code' => 'session#activate', :as => 'activate'

  match 'enewsletter' => 'static#enewsletter'
  match 'blog' => 'static#blog'
  match 'GeneralDynamics' => 'static#general_dynamics'
  match 'UnisysDescriptions' => 'static#unisys_descriptions'
  match 'BNSF-hot-job' => 'static#bnsf_hot_job'

  match 'static/download_docx/*path' => 'static#download_docx'
  match 'static/employer/*path' => 'static#index'
  match 'static/*path' => 'static#index'
  
  match ':controller/:action.:format'
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'
end

app/models/user.rb
require 'digest/sha1'
require "net/http"
require "uri"
require "social"

class User < ActiveRecord::Base

  @@linkedin_profile_api_url = "http://api.linkedin.com/v1/people/~" 

  has_many :authentications, :dependent => :destroy
  has_many :connections, :dependent => :destroy

  has_many :addresses, :as => :addressable, :dependent => :destroy do
    def [](label)
      find(:first, :conditions => ['label = ?', label.to_s.downcase]) rescue nil
    end
  end

  # Inbox entry can reference a resume or a job, depending on the kind of user
  has_many :inbox_entries do
    def contains?(resource, type="Resume")
      !resource.nil? && count(:conditions => ["resource_id = ? AND resource_type = ?", resource.id, type]) > 0
    end
  end
  
  # View in the Inbox / Dashboard and mainly populated by observers.
  has_many :messages, :as => :recipient, :dependent => :destroy, :order => "created_at DESC"
  has_one :message 

  has_many  :registrations, :as => :attendant, :dependent => :destroy, :order => "created_at DESC"
  
  validates_presence_of     :username,                   :if => :login_with_password?
  validates_uniqueness_of   :username,                   :if => :login_with_password?
  validates_length_of       :username, :within => 3..40, :if => :login_with_password?
  validates_presence_of     :password,                   :if => :login_with_password?
  validates_presence_of     :password_confirmation,      :if => :login_with_password?
  validates_length_of       :password, :within => 4..40, :if => :login_with_password?
  validates_confirmation_of :password,                   :if => :login_with_password?

  validates_presence_of     :first_name, :last_name
#  Comented to make required applicant's email
#  validates_presence_of     :email, :if => :recruiter?
  validates_presence_of     :email

  STATUS = ["active", "inactive"]
  
  def login_with_password?
     authentications.to_s.blank?
  end

  def recruiter?
    has_role?("employer_admin") || has_role?("recruiter")
  end

  # ROLES 
  ROLES = [ 'admin', 'sales_rep', "employer_admin", "recruiter", "applicant" ]

  # Check the presence or arg in user's roles. Return true or false
  def has_role?(arg)    
    if arg.is_a?(Array)
      required_roles = arg.collect {|role| role.to_s}
    else
      required_roles = arg.to_s.lines.to_a
    end
    not (self.roles.to_s.split(' ') & required_roles).empty?
  end
  
  # Add role to user's roles. Role should be one of User#ROLES
  def add_role(arg)
    raise ArgumentError, "Invalid role: '#{arg}' (expected one of User::ROLES [#{ROLES.join(', ')}])", caller if !ROLES.include?(arg)
    self.roles = "#{self.roles.to_s} #{arg}".strip if not has_role?(arg)
  end
  
  def remove_role(arg)
    self.roles = (self.roles.split(' ') - arg.lines.to_a).join(' ') if has_role?(arg)
  end

	# Return "humanized" role names for the user
  def humanized_roles
    roles.split(' ').collect {|x| x.titleize}.join(", ")
  end

	# Return an array all site administrators
	def self.administrators
		User.find_by_sql 'select * from users where roles REGEXP "^admin.*|\sadmin.*";'
	end

	# Register for a jobfair. If the user is already registered ignore. This method is not meant
	# to be called directly, see: Applicant#register_for or Recruiter#register_for
	#
	# * Applicants don't have registration's extra information and options must be an empty hash.
	#
	# * Recruiters have additional information in the registration and the options parameter
	# contains the values from the registration form. Recruiter registrations should always be
	# added to the employer's administrator of the recruiter's company (see Reccruiter#register_for).
  def register_for(jobfair, options={})
    (Registration.new({:jobfair => jobfair, :attendant => self}.merge(options)).save!) && (return true) unless self.registered?(jobfair)
    return false

  rescue ActiveRecord::ActiveRecordError => e
    logger.error(e)
    return false
  end


  def update_or_create_address(hs)
    if addresses[hs["label"]].nil?
      addresses << Address.new(hs)
    else
      addresses[hs["label"]].update_attributes!(hs)
    end
  end

  # Virtual Attributes

  # Return complete name as string (title, first, initial, last)
  def name
    [first_name, initial, last_name].select {|x| not x.nil?}.map {|x| x.strip}.join(" ").titleize
  end
  
  def password_confirmation
    password
  end
  
  def is_active?
    status == "active"
  end
  
  def address
    addresses[:primary]
  end
  
  # --------------------------
  #      AUTHENTICATION
  # --------------------------

  # Authenticates a user by their username and unencrypted password.  Returns the user or nil.
  def self.authenticate(username, password)
    user = find_by_username_and_password_and_status_and_activation_code(username, password, "active", nil)

    unless user.nil? 
      user.login_count += 1
      user.last_login_at = Time.now 
      user.save 
    end

    return user
  end

  def encrypt(password, salt)
     Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  
  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 2.weeks
  end
  

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  
  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token = Digest::SHA1.hexdigest("#{email}--#{remember_token_expires_at}")
    save(:validate => false)
  end
  

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(:validate => false)
  end


  # Activates the user in the database.
  def activate
    unless self.recently_activated?
      @activated = true
      self.activated_at = Time.now.utc
      self.activation_code = nil
      self.status = "active" if has_role?(:employer_admin) || has_role?(:applicant)
          
      save(:validate => false)
    end
  end

  def recently_activated?
    @activated
  end
  
  def make_activation_code
    self.activation_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
  end

  def active?
    # the existence of an activation code means they have not activated yet
    activation_code.nil?
  end

  def linkedin_authenticated?
    not self.authentications.find_by_provider("linked_in").nil?
  end

  def fetch_linkedin_profile(fields = ['first-name', 'last-name', 'headline'], access_token = nil, token_secret = nil)

    return if not linkedin_authenticated?

    if access_token == nil || token_secret == nil
      auth = self.authentications.find_by_provider("linked_in")
      access_token = auth.access_token unless auth.nil?
      token_secret = auth.token_secret unless auth.nil?
    end

    Social::LinkedIn.get(@@linkedin_profile_api_url + ":(#{fields.join(',')})", access_token, token_secret) unless access_token.blank?
  end

  def fetch_linkedin_photo

    return if not linkedin_authenticated?

    tmp_file = Tempfile.new("photo_#{id}_#{Time.now}")
    tmp_file.write(Net::HTTP.get(URI.parse(self.picture_url)))
    self.photo = tmp_file
    self.save!
  end

  def fetch_linkedin_connections

    return if not linkedin_authenticated?

    auth = self.authentications.find_by_provider("linked_in")
    raise "Unauthorized: Can't find linkedIn authorization for: #{username}:#{id} (#{name} / #{email})" if auth.nil?

    url="#{@@linkedin_profile_api_url}/connections:(id,first-name,last-name,headline,industry,location,picture-url,positions,api-standard-profile-request)"
    Rails.logger.debug("Fetching: " + url)
    results = Social::LinkedIn.get(url, auth.access_token, auth.token_secret)
    Rails.logger.debug(results.inspect)

    unless results.nil? || results.empty? 

      self.connections.destroy_all

      results["values"].each do |c| 
        connection = Connection.new(
          :provider => "linkedin",
          :unique_identifier => c["id"],
          :first_name => c["firstName"],
          :last_name => c["lastName"],
          :headline => c["headline"], 
          :industry => c["industry"],
          :location => (c["location"]["name"] rescue nil), 
          :profile_url => (c["apiStandardProfileRequest"]["url"] rescue nil),
          :picture_url => c["pictureUrl"]
        )
        unless c["positions"].nil? || c["positions"]["values"].nil?
          positions = []
          positions << c["positions"]["values"]
          positions.flatten.each do |p|
            if(p["is_current"] == "true" || p["is_current"] == true)
              position = Position.new(
                :unique_identifier => p["id"],
                :ticker            => p["company"]["ticker"],
                :company           => p["company"]["name"], 
                :industry          => p["company"]["industry"] || nil,
                :title             => p["title"]
              )
              connection.positions << position
            end
          end
        end
        
        self.connections << connection
      end
    end

    self.save!

  rescue Exception => e
    Rails.logger.error(e.inspect)
  end


  DEFAULT_PASSWORD_LENGTH = 6
   
  NUMBERS_AND_LETTERS_ALPHABET = [
    'A','B','C','D','E','F','G','H',
    'I','J','K','L','M','N','O','P',
    'Q','R','S','T','U','V','W','X',
    'Y','Z','a','b','c','d','e','f',
    'g','h','i','j','k','l','m','n',
    'o','p','q','r','s','t','u','v',
    'w','x','y','z','0','1','2','3',
    '4','5','6','7','8','9'
  ]
    
  def self.get_random_password
    self.generate_password(DEFAULT_PASSWORD_LENGTH)
  end 
    
    
  def self.generate_password(length) 
    password = []
    length.times do
      password.push NUMBERS_AND_LETTERS_ALPHABET[0 + rand(NUMBERS_AND_LETTERS_ALPHABET.size-1)];
    end 
        
    return password.to_s
  end 
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin/layouts/application"


  before_filter :login_required
  require_role(:admin)

  before_filter :load_model, :except => ["index", "new", "create"]


	def index
		@users = User.administrators
	end

	def edit
	end

	def update
		@user = User.find params[:id]
		@user.update_attributes(params[:user])
		@user.save!

		flash[:notice] = "Your Changes have been saved"
		render :action => "edit"

	rescue
	  @user.valid?
		render :action => "edit"

	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		@user.save!

		redirect_to(admin_users_path)

	rescue
		@user.valid?
		render :action => "new"
	end

	def destroy
		@user.destroy
		redirect_to admin_users_path
	end

	def skip_email_verification
        @user.activate if params[:enable] == "yes"
        render :nothing => true
	end

  private 

  def load_model
    @user = User.find params[:id]
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
<fieldset>
	<legend>Name and Email</legend>
	
	<div class="inline">
		<%= form.text_field :first_name, :class=> "name M big_font" %>
		<%= form.text_field :last_name, :class => "name M big_font" %>
	</div>
	<%= form.text_field :email, :class=>"big_font L", :id => "user_email" -%>
</fieldset>

<script>
 Event.observe("user_email", "change", function(event) {
    if($('user_username').value == '') {
        $('user_username').value = $('user_email').value;
    }
 });
</script>


<% unless @social_media_account == true %>
<fieldset>
	<legend>Account Login Information</legend>
	
	<div style="margin:8px 0px">
      <div class="round-corners light-highlight">
         <div style="padding:0px 5px">Please enter whatever username and password you desire. (Default username is your email address)</div>
      </div>
	</div>
	<div class="inline">
	<%= form.text_field :username, :class => "all_lower" , :disabled => !form.object.new_record?, :id => "user_username"-%>
	<%= form.select(:roles, (@valid_roles || User::ROLES).collect{|role| [role.humanize, role]} , {:include_blank => true}) if @current_user && @current_user.has_role?('admin')  %>
	</div>
	<div class="inline">
      <%= form.password_field :password, :label => "Password (4 to 7 characters required)" %>
      <%= form.password_field :password_confirmation %>
	</div>
</fieldset>
<% end %>

app/views/user/_listed_users.html.erb
<style>
  ul#users_list li {
    margin-bottom: 3px; 
    padding: 6px 3px;
    border: 1px solid #CCC; 
  }

  ul#users_list a {
    text-decoration:none
  }

  ul#users_list a:hover {
    text-decoration: none;
    color: white; 
    background: blue;
  }
</style>

<h2 style="background: #010C2A; color:#FFF; padding-top: 2em; padding-left: 4px; margin: 0;" >Recruiters</h2>
<ul id="users_list">
  <%  (@users.sort {|a,b| a.name <=> b.name}).each do |user| %>
    <li><%= link_to user.name, edit_user_path(user.id)-%>&nbsp;(last login: <%=user.last_login_at.to_formatted_s(:short) rescue "Never" -%>)</li>
  <% end %>
</ul>

app/views/user/new_or_link.html.erb
<div id="login_box" style="font-family: Arial; font-size: 1em; height: 450px; padding: 0;">
  <div id="message">
    To enable login to your Corporate Gray account via LinkedIn, please complete the information below.
  </div>
  <br/>

  <table id="options">
    <tr>
      <td id="login_form">
        <div style="font-weight: bold">If you have a Corporate Gray account:</div>
        <br/>
        <div>
          <%= form_tag link_authentications_path do %>
            <%= hidden_field_tag :provider, params[:provider] %>

            <fieldset style="border: 0px solid #FFF; margin-top: 0; padding: 0;">
              <div>
                <label>Username</label><br/>
                <%= text_field_tag :username %>
              </div>

              <div style="height: 66px">
                <label>Password</label><br/>
                <%= password_field_tag :password %>
              </div>
              <%= link_to "Forgot your Password?, click here", password_reminder_sessions_path, :class => "action_link" %>
            </fieldset> 

            <br/>
            <%= submit_tag "login", :id => "submit_button", :class => "large cyan xbutton" %>

          <% end %>
        </div>
      </td>
      <td><b>I'm a New:</b><br/><%= link_to "Job Seeker", new_applicant_path, :class=>"xbutton red", :style => 'color: #FFF; font-size: 20px; margin-top: 0.5em;' %></td>
      <td><b>I'm a New:</b><br/><%= link_to "Employer", new_employer_path, :class=>"xbutton red", :style => 'color: #FFF; font-size: 20px; margin-top: 0.5em;' %></td>
    </tr>
  </table>

</div>
<br/>
<hr/>

<style>

  #message {
    padding: 1em;
    margin: 1em;
    margin-bottom: 0;
    border: 3px solid #008000;
    border-radius: 5px;
    background: #0C0;
    color: white;
  }
  
  #login_box p {
    margin: 1em;
    line-height: 1.7em;
    color: #4C4C4C;
  }

  #options {
    width: 100%;
  }

  #options td {
    width: 25%;
    text-align: center;
    vertical-align: top;
  }

  #options td a.xbutton {
    color: #FFF; 
    font-weight: bold;
    padding: 10px 15px;
  }

  td#login_form {
    width: 50%;
    text-align: left; 
    padding-left: 1em;
    border-right: 1px solid #CCC;
  }

  #createAccount {
    float:left; 
    width: 400px; 
    height: 400px; 
    border-right: 1px dotted #4c4c4c; 
    border-top-left-radius: 5px;
    border-bottom-left-radius: 5px;
    padding: 0; 
    padding-right: 1.5em; 
    background: url(/images/60degree_gray.gif);
  }
  
  #createAccount td {
    width: 50%;
    padding: 0 1em;
    vertical-align: top;
    color: #4c4c4c;
    line-height: 1.5em;
  }
    
  #createAccount td b {
    color: #BD0000;
    font-weith: bold;
  }

  label {
    font-size: 1.1em; 
    margin-left: 2px;
    font-weight: bold; 
  }

  input[type=text], input[type=password] {
    font-size: 1.5em;
    padding: 3px;
    margin-top: 5px;
    margin-bottom: 1em;
    border: 1px solid #ccc;
  }
</style>