config/routes.rb
Cgray::Application.routes.draw do

  resources :sitemap do 
    collection do 
      get :basic
      get :jobfairs
      get :jobs
      get :employers
      get :static
    end
  end

  resources :users, :controller => "user"
  
  resources :sessions, :controller => 'session' do
    collection do
      get :password_reminder 
    end
  end

  resources :authentications, :controller => 'authentication' do
    collection do
      post :link
    end
  end

  resources :applicants, :controller=> 'applicant' do 

    collection do
      get  :deactivate
      post :process_deactivation 
    end

    member do 
      post :apply 
      post :enable_social_login
      get  :photo
    end
  end

  resources :connections do
    member do
      get :photo
    end
  end

  resources :employers, :controller => 'employer' do

    collection do
      get :job_fairs 
      get :services
    end

    member  do  
      get :public_profile 
    end

    resources :recruiters, :controller => 'recruiter' do 
      member do
        get :current_status 
        get :dashboard 
      end
    end

    resources :ofccp do 
      collection do
        post :download_to_excel
        post :download 
      end
    end

  end

  resources :jobs do 
    
    collection do 
      get :search 
      get :quick_search 
      post :auto_complete_for_employer_name 
    end

	member do 
      get :repost 
      get :apply 
      get :apply_notify
      get :add_to_inbox
      get :remove_from_inbox 
      get :public_profile 
    end

  end

  resources :resumes do 

    collection do 
      get :search
      get :quick_search 
      get :guest_search
      get :guest_index
    end

	member do 
      get :add_to_inbox 
      get :remove_from_inbox 
      get :print 
     post :forward 
      get :download 
      get :attachment 
    end
  end

  resources :positions do
    member do
      post :validate
    end
  end

  resources :educations do
    member do
      post :validate
    end
  end

  resources :jobfairs, :controller => "jobfair" do 
    member do 
      get :registered_employers 
    end

	   resources :registrations
  end

  resources :messages

  resources :registrations do
    collection do 
      get  :new_from_affiliate 
      post :post_from_affiliate 
    end
  end

  
  namespace :admin do 

    resources :jobfairs

	   resources :registrations do
      member do 
        get :enable_search 
      end
    end

    resources :employers do
      member do 
        post :administrator_name 
      end

      resources :recruiters do 
        collection do 
          get :download_to_excel 
        end
      end

      resources :jobs
    end

    resources :recruiters do 
      collection do 
        post :auto_complete_for_employer_name 
        post :update_employer 
        get  :edit_employer
      end
    end

    resources :applicants do 
      collection do 
        post :upload
        post :download_to_excel 
      end

    end

    resources :resumes do 
      collection do
        get :search 
      end

      member do 
        get :download 
        get :attachment 
       post :forward
      end

    end

    resources :users do 
      member do
        get :skip_email_verification 
      end
    end

	   resources :ofccp do
      collection do 
        post :download_to_excel 
      end
    end

  end 
  
  
  root :to => 'welcome#index'
  match 'welcome' => 'welcome#index', :as => 'welcome' 

  match 'admin' => "admin/welcome#index", :as => "admin"
  match 'request_authsub_authorization' => "admin/welcome#request_authsub_authorization", :as => "admin"

  match '/auth/:provider/callback' => 'authentication#create'
  match '/auth/failure' => 'authentication#failure'

  match 'login' => 'session#new', :as => 'login'
  match 'logout' => 'session#destroy', :as => 'logout'
  match 'activate/:activation_code' => 'session#activate', :as => 'activate'

  match 'enewsletter' => 'static#enewsletter'
  match 'blog' => 'static#blog'
  match 'GeneralDynamics' => 'static#general_dynamics'
  match 'UnisysDescriptions' => 'static#unisys_descriptions'
  match 'BNSF-hot-job' => 'static#bnsf_hot_job'

  match 'static/download_docx/*path' => 'static#download_docx'
  match 'static/employer/*path' => 'static#index'
  match 'static/*path' => 'static#index'
  
  match ':controller/:action.:format'
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'
end

app/models/resume.rb
class Resume < ActiveRecord::Base

  Resume::VISIBILITY = ['public', 'private', 'confidential']

  belongs_to :applicant

  has_many :inbox_entries, :as => :resource
	
  # :url  => "attachments/:attachment/:id_resume.:content_type_extension"
  has_attached_file	:attached_resume,
    :path => ":rails_root/paperclip/:attachment/:id_resume.:content_type_extension",
    :url  => ":id/attachment.:content_type_extension"

  validates_attachment_presence	:attached_resume, 
    :if => lambda { |res| res.input_method == "upload"}, 
    :message => ".You must select a file to upload"

  validates_attachment_size	:attached_resume, :less_than => 512.kilobytes


  after_save {applicant.__elasticsearch__.index_document if applicant.status == 'active'}
  
  def data
    filename = self.attached_resume.path || (self.attached_resume.queued_for_write[:original].path rescue nil)
    (filename ?  File.read(filename) : "")
  end

  def posted_date
    (updated_at || created_at).to_date
  end

  def posted_date_for_solr
    posted_date.to_s(:yyyymmdd)
  end

  def posted_months_ago
    tstamp = posted_date
    if tstamp >= 1.month.ago.to_date
      return "one-month"
    elsif tstamp >= 3.month.ago.to_date
      return "three-months"
    elsif tstamp >= 6.month.ago.to_date
      return "six-months"
    end
    return "over-six-months"
  end


  # Deprecated: This method is not being used, it can be deleted. 
  # This is also incorrect since it does not account for .doc file type. 
  # Action: Comment and delete if no side-effects. 
  # def current_text_format
    # (attached_resume.path(:docx) && :docx) || (attached_resume.path(:html) && :html) || :text
  # end

  def has_body? format
    formats = [].push(format).flatten
    formats.any? { |fmt| File.exists?(attached_resume.path(fmt)) }
  end

  def get_body format=nil

    resume_body, content_type = nil
    formats = [].push(format || ["pdf","doc", "docx", "html", "txt"]).flatten
    formats.each do |fmt|
      if File.exists?(attached_resume.path(fmt))
        resume_body = File.read(attached_resume.path(fmt))
        content_type = Mime::Type.lookup_by_extension(fmt).to_s
        break
      end
    end
    return [resume_body, content_type]

  end


  def formatted_text(fmt=:web)

    if(fmt == :web)

      if !attached_resume.path(:html).nil? && File.exist?(attached_resume.path(:html))
        File.open(attached_resume.path(:html), "r").read
      else attached_resume.path(:txt).nil? && File.exit?(attached_resume.path(:txt))
        File.open(attached_resume.path(:txt), "r").read.gsub(/[\r\n]{1,2}/, "<br/>")
      end

    elsif fmt == :text && attached_resume.path(:txt).nil? && File.exit?(attached_resume.path(:txt))
      File.open(attached_resume.path(:txt), "r").read.gsub(/[\r\n]{1,2}/, "<br/>")
    end

  end

end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ResumesController

  include ApplicationHelper

  # We don't need these methods here; Let's remove them for 
  # security's sake. 
#  remove_method :quick_search
#  remove_method :new
#  remove_method :create
#  remove_method :edit
#  remove_method :update
#  remove_method :print
#  remove_method :add_to_inbox
#  remove_methid :remove_from_inbox
#  remove_method :forward
#  remove_method :valid_attachment_extension?

  layout "admin/layouts/application"

  before_filter :login_required
  dont_require_role(:applicant_employer_admin_recruiter)
  dont_require_role(:employer_admin_recruiter)
  dont_require_role(:applicant) && dont_require_role(:recruiter) && dont_require_role(:employer_admin) && require_role(:admin)

  def index; end


  def search

    # Skip processing of empty queries
    return if params[:q].to_s.blank?

    # Fix unclosed quotes, and uppercase logical opperands.
    unless(params[:q][:keyword].to_s.blank?)
      query = params[:q][:keyword]
      query = query.delete('"') if query.count('"') % 2 > 0
      query = query.delete("'") if query.count("'") % 2 > 0
    end

    how_many = (params[:q][:posted_date_for_solr] == "one-month" and 1) || (params[:q][:posted_date_for_solr] == "three-months" and 3) || 6

    options = {
      last_name:              params[:q][:applicant_last_name],
      state:                  params[:q][:state],
      security_clearance:     params[:q][:security_clearance],
      type_of_applicant:      params[:q][:type_of_applicant],
      branch_of_service:      params[:q][:branch_of_service],
      education_level:        params[:q][:education_level],
      how_many:               how_many,
      willing_to_relocate:    params[:q][:willing_to_relocate].to_s,
      job_fair_registrations: params[:q][:job_fair_registrations]
    }

    @applicants = Applicant.search(query, options).page(params[:page] || 1).per_page(Constants::PAGE_SIZE).records

    #@applicants = do_search(params[:page] || 1)

    if params[:is_download]

      applicants = []

      @applicants.each do |applicant| 
        applicants << applicant
      end

      if(@applicants.total_pages > 1)
        page = 2
        while page < @applicants.total_pages
          #@applicants = do_search(page)
          @applicants = Applicant.search(query, options).page(page).per_page(Constants::PAGE_SIZE).results
          @applicants.each do |applicant|
            applicants << applicant
          end
          page = page + 1 
        end
      end

      xml = Builder::XmlMarkup.new
      result = models_to_excel(xml, applicants, {
          :include => [
            "username", "status",
            "first_name", "last_name", "email",
            "education_level", 
            "security_clearance", 
            "type_of_applicant", 
            "willing_to_relocate", 
            "resume_posted_date",
            "state", 
            "city"
          ]
      })

      send_data(result, :filename => "search_results.xls", :type => "application/xls", :disposition => "inline");
      return
    end


  end


  private

#  def do_search(page)
#    
#    # Fix unclosed quotes, and uppercase logical opperands.
#    unless(params[:q][:keyword].to_s.blank?)
#      query = params[:q][:keyword]
#      query = query.delete('"') if query.count('"') % 2 > 0
#      query = query.delete("'") if query.count("'") % 2 > 0
#    end
#
#    applicants = Applicant.search do
#
#      paginate(:page => page, :per_page => Constants::PAGE_SIZE ) 
#      order_by(:posted_date, :desc)
#
#      if(query)
#        keywords(query)
#      else
#        with :last_name, params[:q][:applicant_last_name].downcase
#      end
#
#      with(:state).any_of(([] << params[:q][:state]).flatten) unless params[:q][:state].to_s.blank?
#
#      with(:type_of_applicant).any_of(([] << params[:q][:type_of_applicant]).flatten) unless params[:q][:type_of_applicant].to_s.blank?
#      with(:branch_of_service).any_of(([] << params[:q][:branch_of_service]).flatten) unless params[:q][:branch_of_service].to_s.blank?
#      with(:security_clearance).any_of(([] << params[:q][:security_clearance]).flatten) unless params[:q][:security_clearance].to_s.blank?
#
#      unless params[:q][:posted_date_for_solr].to_s.empty?
#        how_many = (params[:q][:posted_date_for_solr] == "one-month" and 1) || (params[:q][:posted_date_for_solr] == "three-months" and 3) || 6
#        with(:posted_sate_for_solr).between(how_many.months.ago.to_date.to_s(:yyyymmdd), Date.today.to_s(:yyyymmdd))
#      end
#
#      with(:willing_to_relocate).equal_to(params[:q][:willing_to_relocate]) unless params[:q][:willing_to_relocate].nil?
#
#      job_fair_registrations = [params[:q][:job_fair_registrations]].flatten.compact 
#      job_fair_registrations = job_fair_registrations.select { |jfr| !jfr.to_s.blank? }
#
#      with(:job_fair_registrations).any_of(job_fair_registrations) unless job_fair_registrations.empty?
#
#    end
#
#    return applicants
#
#  end

end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/resumes/_resume_forward_form.html.erb
<div style="font-weight: bold; margin-bottom:5px;color:black; cursor:default;">Recipients' Email (separated by comma)</div>
<%= form_for :forward, :url => forward_resume_path(resume.id), :remote => true do |f| %>
<%= f.text_field :recipients %>
<div class="actionButton" style="float:right; clear:none;">
  <div>
    <button type="submit">Send</button>
  </div>
</div>
<% end %>
<script>
  $$('#forward_resume_form')[0].on('ajax:complete', function() { forwardPanel.hide(); } );
</script>

app/views/resumes/_search_form.html.erb
<div class="search-block">

  <% unless current_user.nil? %>
    <div style="margin-bottom: 1em; background: whitesmoke; border-radius: 3px; padding: 0.5em;">
        <div style="padding:4px 12px 4px 8px;text-align: justify;">
          <% if !current_user.employer.resume_search_expire_at.to_s.blank? && current_user.employer.resume_search_privileges? %>
            You have full resume search privileges until: 
            <div style='text-align:center'><%= current_user.employer.resume_search_expire_at.to_s(:mmddyyyy) -%></div>
          <% else %>
            Resume access is currently limited to the resumes from your previously registered job fairs. 
            To purchase full resume search access, click here
            <%= link_to "Carl@CorporateGray.com", "mailto:carl@corporategray.com", :style=> "color:inherit;" %>.</b>
          <% end %>
        </div>
    </div>
  <% end %>

  <%= form_tag current_user.nil? ? guest_search_resumes_path : search_resumes_path, :id =>"search_form", :method => :get  do %>
    <% if !current_user.nil? && current_user.employer.is_federal_employer? %>
      <label style="font-weight:bold; float:left; clear:both; margin-bottom: 15px; color: #BD0000;">
        Enter your internal requisition # (Job Code)
        <%= text_field_tag "job_code", job_code, :style=>"width:100%; float:left; clear:both; margin-top: 5px;" %>
      </label>
    <% end %>
          
    <label style="font-weight:bold; white-space:nowrap;">
      Search by Keyword
      <%= text_field_tag "q[keyword]", q[:keyword], :style =>"width: 300px; float: left; clear : both; margin-top: 5px;" %>
      <div style="clear:both; float:left; padding-top:2px; padding-bottom: 5px; font-weight: normal; font-style: italic; font-size: 0.95em; color:#BD0000;">
        You can use multiple keywords, "quotes to search <br/>phrases" and +/- for mandatory/excluded terms <br/>(i.e: "program manager" +software -aviation)
      </div>
    </label>

    <label style="margin-bottom: 5px; margin-top: 10px; font-weight: bold; float:left; clear:both; white-space:nowrap">
        Search by Last Name
        <%= text_field_tag "q[applicant_last_name]", q[:applicant_last_name], :style =>"width: 300px; float: left; clear : both; margin-top: 5px;" %>
    </label>

    <a class="button" style="float:left; clear:both; margin-top: 3px; margin-left: 0px; margin-bottom: 20px;" onclick="$('search_form').submit(); return false;" href="#"><span>Search</span></a>
    <hr style="float:none; clear:both; color: #DDD;"/>

    <!-- rank, branch_of_service, security_clearance, education_level, state, availability, posted_by, jobfair attendance -->
    <div class="filter-block">
      <h3>Filters:</h3>

      <div id="by-state" class="css-filter">
        <p>By State</p>
        <ul>
          <li><%=select_tag("q[state][]", options_for_select(options_from_hash(Constants::STATE_APO), q[:state] ), :multiple => true, :size => 4) %></li>
        </ul>
      </div>

      <div id="by-rank" class="css-filter">
        <p>By Rank</p>
        <ul>
          <li><%=select_tag("q[type_of_applicant][]", options_for_select(options_from_hash(Constants::TYPE_OF_APPLICANT), q[:type_of_applicant] ), :multiple => true, :size => 4)-%></li>
        </ul>
      </div>

      <div id="by-branch-of-service" class="css-filter">
        <p>By Branch Of Service</p>
        <ul>
          <li><%=select_tag("q[branch_of_service][]", options_for_select(options_from_hash(Constants::BRANCH_OF_SERVICE), q[:branch_of_service] ), :multiple => true, :size => 4)-%></li>
        </ul>
      </div>

      <div id="by-security-clearance" class="css-filter">
        <p>By Security Clearance</p>
        <ul>
          <li><%=check_box_tag 'q[security_clearance][]', 3, (q[:security_clearance].include?("3") rescue true) %>None&nbsp;<span id="security_clearance_3"></span></li>
          <li><%=check_box_tag 'q[security_clearance][]', 1, (q[:security_clearance].include?("1") rescue true) %>Secret&nbsp;<span id="security_clearance_1"></span></li>
          <li><%=check_box_tag 'q[security_clearance][]', 2, (q[:security_clearance].include?("2") rescue true) %>Top Secret&nbsp;<span id="security_clearance_2"></span></li>
          <li><%=check_box_tag 'q[security_clearance][]', 0, (q[:security_clearance].include?("0") rescue true) %>Unspecified&nbsp;<span id="security_clearance_0"></span></li>
        </ul>
      </div>

      <div id="by-education" class="css-filter">
        <p>By Education Level</p>
        <ul>
          <li><%=check_box_tag 'q[education_level][]', 1, (q[:education_level].include?("1") rescue true) %>High School / GED&nbsp;<span id="education_level_1"></span></li>
          <li><%=check_box_tag 'q[education_level][]', 3, (q[:education_level].include?("3") rescue true) %>Associates Degree&nbsp;<span id="education_level_3"></span></li>
          <li><%=check_box_tag 'q[education_level][]', 4, (q[:education_level].include?("4") rescue true) %>Bachelors Degree or Higher&nbsp;<span id="education_level_4"></span></li>
          <li><%=check_box_tag 'q[education_level][]', 0, (q[:education_level].include?("0") rescue true) %>Unspecified&nbsp;<span id="education_level_0"></span></li>
        </ul>
      </div>

      <div id="by-post-date" class="css-filter">
        <p>By Post Date</p>
        <ul>
          <li><%= select_tag 'q[posted_date]', options_for_select([['All', ''], ['One Month Ago', 'one-month'], ['Three Months Ago', 'three-months'], ['Six Months Ago', 'six-months']], q[:posted_date] ) -%></li>
        </ul>
      </div>

      <div id="willing-to-relocate" class="css-filter">
        <p>By Willingness to Relocate</p>
        <ul>
          <li><%= select_tag 'q[willing_to_relocate]', options_for_select([["Don't Care", ''], ['Yes', 'true'], ['No', 'false']], q[:willing_to_relocate]) -%></li>
        </ul>
      </div>

      <% if !current_user.nil? && current_user.employer.registrations.any? %>
        <div id="by-jobfair-attendance" class="css-filter">
          <p>By Job Fair Attendance</p>
          <ul>
            <li><%=  select_tag "q[job_fair_registrations]", options_for_select([["Select All", ""]] + current_user.employer.registrations.collect {|reg| [truncate(reg.jobfair.name, :length => 40), reg.jobfair.id] if reg.enable_search == true || current_user.employer.resume_search_allowed?}.compact, q[:job_fair_registrations]) -%></li>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>

  <a class="button" style="float:left; clear:both; margin-top: 15px; margin-left: 5px; margin-bottom: 20px;" onclick="$('search_form').submit(); return false;" href="#"><span>Search</span></a>

</div>

app/views/resumes/edit.html.erb
<% content_for :page_title do %>
	Your Profesional Resume & Cover Letter
<% end %>

<% content_for :head do %>

  <style>
    .modal {
      width:650px; 
      height:460px; 
    }
	
	#resume_samples a {
		text-decoration: none;
		color: blue;
	}
    #resume_samples a:hover {
      text-decoration: underline;
    }
	#resume_samples li {
		margin-bottom: 2px;
	}
  </style>

  <script language="javascript">
    var modal;
    document.observe("dom:loaded", function() {
      //Modal Window  
      modal = new Control.Modal($('show-modal'),{  
          overlayOpacity: 0.75,  
          className: 'modal',  
          method: 'get',
          fade: true  
      });  
    });
  </script>
<% end %>


<div style="line-height: 1.8em; font-size: 16px; color: #4c4c4c; margin-bottom: 10px;">
  <p> You can review the sample documents below to craft an 
  effective resume. Once you are ready, use the button below 
  to upload your resume and cover letter in MS Word format:</p>
</div>

<div style="text-align:center">
  <%= link_to "Upload Resume", edit_resume_path(@resume), :id => "show-modal", :class => 'xbutton red large' %>
</div>

<% content_for :right do %>

  <div style="clear:both; float:none; margin-top: 0px">
    <%= link_to "Military-to-Civilian Skills Translator", "http://online.onetcenter.org/crosswalk", :style=>"color:#000; text-decoration:underline;font-size: 18px;", :target => '_blank' -%></span>
  </div>

  <div style="margin-top: 25px">
    <h2 style="margin-top:0px">Cover &amp; Approach Letters</h2>
    <ul id="resume_samples">
      <li><%= link_to "Cover Letter", "/cover_letters/Cover_Letter.pdf", :target => '_blank' -%></li>
      <li><%= link_to "Approach Letter", "/approach_letters/ApproachLetter.pdf", :target => '_blank' -%></li>
    </ul>
    <div style="float:none; clear:both"></div>
  </div>

  <div style="margin-top: 25px;">
    <h2 style="margin-top:0px">Sample Resumes </h2>
    <ul id="resume_samples">
        <li><%= link_to "Combat Engineer", "/static/download_docx/CombatEngineer.docx", :target => '_blank' -%></li>
        <li><%= link_to "Electrician", "/static/download_docx/Electrician.docx", :target => '_blank' -%></li>
        <li><%= link_to "Helicopter Maintenance", "/static/download_docx/HelicopterMaintenanceSupervisor.docx", :target => '_blank' -%></li>
        <li><%= link_to "Homeland Security", "/static/download_docx/HomelandSecurityManager.docx", :target => '_blank' -%></li>
        <li><%= link_to "Human Resources", "/static/download_docx/HumanResourcesManager.docx", :target => '_blank' -%></li>
        <li><%= link_to "Law Enforcement", "/static/download_docx/Law-Enforcement.docx", :target => '_blank' -%></li>
        <li><%= link_to "Maintenance Technician", "/static/download_docx/MaintenanceTechnician.docx", :target => '_blank' -%></li>
        <li><%= link_to "Network Administrator", "/static/download_docx/NetworkAdministrator.docx", :target => '_blank' -%></li>
    </ul>
  </div>

  <div style="margin-top: 25px;">
    <h2 style="margin-top:0px">Thank You Letters</h2>
    <ul id="resume_samples">
      <li><%= link_to "Job Offer Acceptance.pdf",	"/thankyou_letters/Thank_You_Letter_Job_Offer_Acceptance.pdf", :target => '_blank' -%></li>
      <li><%= link_to "Post Informational Interview.pdf", "/thankyou_letters/Thank_You_Letter_Post_Informational_Interview.pdf", :target => '_blank' -%></li>
      <li><%= link_to "Post Job Interview.pdf", "/thankyou_letters/Thank_You_Letter_Post_Job_Interview.pdf", :target => '_blank' -%></li>
    </ul>
    <div style="float:none; clear:both"></div>
  </div>

<% end %>


<style>


</style>

app/views/resumes/guest_search.html.erb
<% content_for :page_title do %>
  <% if @applicants.nil? || @applicants.results.empty? %>
    Search Resumes on Corporate Gray Online
  <% else %>
    Found <%= @applicants.nil? ? 0 : @applicants.total%> Job Seekers Matching Your Criteria
  <% end %>
<% end %>

<% content_for :title_tag do %>
  <%= @applicants.nil? ? "Search Resumes" : "Found #{@applicants.total} Job Seeker(s)" %>
<% end %>

<div id="message" style="margin: 4px;"></div>

<% if !@applicants.nil? && !@applicants.results.empty? %>

  <div style="margin-bottom: 30px;">
    <p>If you have resume search service:</p>

    <div style="margin-top: 20px">
      <%= link_to "Login to Your Account", new_session_path, :class => "flat-button flat-button-blue", :style => "display: inline-block; text-align: center; width: 200px" %>
    </div>
    <br/>
    <p>If you do not have resume search service and would like to order, email: <%=link_to "#{UserMailer.sales_email}", "mailto:#{UserMailer.sales_email}?subject=Resume%20Search%20Status"%></p>

  </div>

<% else %>

  <div style="margin:3px;">
    <p>Search our extensive resume database, most of which are military-experienced candidates! Unlimited resume search for all your recruiters.</p>

    <div style="margin-top: 20px">
      <%= link_to "Create an Employer Account", new_employer_path, :class => "flat-button flat-button-red", :style => "display: inline-block; text-align: center; width: 200px" %>
      &nbsp;
      <%= link_to "Login to Your Account", new_session_path, :class => "flat-button flat-button-blue", :style => "display: inline-block; text-align: center; width: 200px" %>
    </div>

    <h3>Corporate Gray Online Rates</h3>

    <p><b>Per month:</b> $500 to search the resume database and post all of your jobs</p>
    <ul>
      <li>Includes one hour of customized support from a Corporate Gray Online representative.</li>
      <li>15% discount for a contract of 2 or more months.</li> 
    </ul>

    <br/>

    <p><b>1 year:</b> $5,000 to search the resume database and post all of your jobs</p>
    <ul>
      <li>Includes one hour of customized support for each month purchased.</li>
    </ul>
    <br/>

    <p><i>Note: The above rates are ad agency commissionable at 15%.</i></p>
 
    <h3>Job Wrapping Service</h3>
    <p>We'll do a daily scrape of all the jobs on your website at a cost of $500/month. Three-month minimum. Requires no work at your end!</p>

    <br/>


  </div>

<% end %>

<%= render :partial => "/shared/cgo_book_sponsor" %>

<% content_for :right do %>
  <%= render :partial => "search_form", :locals => {:q => params[:q] || {}, :job_code => params[:job_code] || nil } %>
<% end %>

app/views/resumes/quick_search.html.erb
<% if @resumes.nil? %>

								<div style="cursor:pointer;" onclick="Effect.Fade('quick-search-results', {duration: 0.75});">
																<%= image_tag "/images/icns/aesthetica/16x16/warning.png", :style=>"margin-right: 5px; vertical-align: bottom;"%>
																You must enter a search keyword in the space above (i.e. 'engineer')
								</div>

<% elsif @resumes.docs.empty? %>

								<div style="cursor:pointer;" onclick="Effect.Fade('quick-search-results', {duration: 0.75});">
																<%= image_tag "/images/icns/aesthetica/16x16/warning.png", :style=>"margin-right: 5px; vertical-align: bottom;"%>
																No resumes found, please try similar keywords
								</div>

<% else %>
								<div style="cursor:pointer;" onclick="$('quick-search-results').hide();">
																<h3 style="margin-top: 3px;float:left;clear:none; margin-bottom: 3px;"><%= "Showing 3 results out of #{@resumes.total} in our database" -%></h3>
																<%= image_tag "/images/icns/custom/16x16/close.gif", :style=>"float:right; clear:none; margin-right: 5px;"-%>
								</div>
								<ul style="float:none; clear:both; padding-top: 5px; margin-right: 8px; border-top: 1px solid #CCC;">
																<% 3.times do |i| %>
																								<li style="padding-bottom: 5px; padding-left: 10px;">
																																<%= truncate("<b>#{@resumes.docs[i].applicant.first_name}, #{@resumes.docs[i].applicant.last_name[0..0]}:</b> #{try {@resumes.docs[i].applicant.address.city_state} }", 80) -%>
																								</li>
																<% end %>
								</ul>
								<div style="text-align: right; margin-top: 5px; margin-right: 5px;" ><%= link_to "Want to see more? Register or Login", applicants_path, :class=>"action_link"%></div>
<% end %>